#!/bin/bash
# Author: 寒露凝冰
# Verison: 1.3
# Update Time: 2017年11月21日

# This script is used to start,restart,stop tomcat or osgi and 
# clean it's log


# RUN_TOMCAT_NAME represent tomcat name which is running
# TOMCAT_LIST represent all tomcat name which in a specific directory
RUN_TOMCAT_NAME=(`ps aux|grep tomcat|grep -v grep|awk '{print $12}'|cut -d= -f2|awk -F'/conf' '{print $1}'`)
TOMCAT_LIST=`ls /server/*_tomcat* -d`


# Function tomcatallstart is used to start all tomcat
tomcatallstart () {
	echo "$TOMCAT_LIST"
	for START_TOMCAT in $TOMCAT_LIST;do
		$START_TOMCAT/bin/startup.sh
		sleep 5
	done
}


# Function tomcatstart is used to start tomcat
tomcatstart () {
	echo "选择要启动 Tomcat 的编号："
	select START_TOMCAT_NAME in $TOMCAT_LIST;do
		i=0
		for TOMCAT_RUNNING in ${RUN_TOMCAT_NAME[*]};do
			if [ $START_TOMCAT_NAME = $TOMCAT_RUNNING ];then
				echo $START_TOMCAT_NAME is already runnig.
				i=1
			fi
		done
		
		[ $i -eq 0 ] && $START_TOMCAT_NAME/bin/startup.sh && sleep 5
		read -p "退出启动程序请输入 1，继续按回车键：" INPUT1
		[ "$INPUT1" = "1" ] && break
	done
}


# Function osgistart is used to start osgi
# RUN_OSGI_NAME osgi names which is running
# OSGI_LIST names of all osgi prefix
RUN_OSGI_NAME=(`ps aux|grep karaf|grep -v grep|awk '{print $20}'|cut -d= -f2`)
OSGI_LIST=`ls /server/*karaf* -d`
# Function tomcatstart is used to start osgi
osgistart () {
	echo "选择要启动 OSGI 的编号："
	select START_OSGI_NAME in $OSGI_LIST;do
		j=0
		for OSGI_RUNNING in ${RUN_OSGI_NAME[*]};do
			if [ $START_OSGI_NAME = $OSGI_RUNNING ];then
				echo $START_OSGI_NAME is already running.
				j=1
			fi
		done

		[ $j -eq 0 ] && $START_OSGI_NAME/bin/start && sleep 5
		read -p "退出OSGI启动请输入1，继续请按回车键：" INPUT2
		[ "$INPUT2" = 1 ] && break
	done
}


# Function osgiallstart is used to start all osgi
osgiallstart () {
	for START_OSGI in $OSGI_LIST;do
		$START_OSGI/bin/start
		sleep 5
	done
}


# Function stoposgi close osgi
stoposgi () {
	for STOP_OSGI in $RUN_OSGI_NAME;do
		$STOP_OSGI/bin/stop
		sleep 5
	done
}


# Function stoptomcat close tomcat
stoptomcat () {
	for STOP_TOMCAT in ${RUN_TOMCAT_NAME[*]};do
		$STOP_TOMCAT/bin/shutdown.sh
		sleep 5
		res=`ps aux|grep "$STOP_TOMCAT"|grep -v grep|awk '{print $2}'`
		if [ -n "$res" ];then
			kill -9 $res
		fi
	done
}

# Function deletelog clean tomcat's log
deletelog () {
	for TOMCAT_NAME in $TOMCAT_LIST;do
		cat /dev/dull >$TOMCAT_NAME/logs/catalina.out
	done
}


# Now, invoke functions
case $1 in
	--start)
		tomcatstart
		osgistart
		;;
	--startall)
		tomcatallstart
		osgiallstart
		;;
	--stopall)
		stoptomcat
		stoposgi
		;;
	--restartall)
		stoptomcat
		stoposgi
		tomcatallstart
		osgiallstart
		;;
	--cleanlog)
		deletelog
		;;
	--help|*)
		echo "Usage:$0 --start|--startall|--stopall|--restartall|--cleanlog"
		;;
esac
